"""auto update

Revision ID: 29138547422c
Revises: 3ebe4a0a5904
Create Date: 2026-02-07 21:44:14.833916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29138547422c'
down_revision: Union[str, Sequence[str], None] = '3ebe4a0a5904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_regulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('regulation_category', sa.String(), nullable=False),
    sa.Column('regulation_title', sa.String(), nullable=False),
    sa.Column('regulation_content', sa.String(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('max_multiplier', sa.Float(), nullable=True),
    sa.Column('required_days', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_regulations_id'), 'state_regulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_regulations_id'), table_name='state_regulations')
    op.drop_table('state_regulations')
    # ### end Alembic commands ###