import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, ArrowLeft, ArrowRight, DollarSign, AlertTriangle, Shield, CheckCircle } from "lucide-react";

const CASE_STUDIES = [
  {
    title: "Landlord Avoids $8,400 Penalty with Security Deposit Fix",
    location: "San Francisco, CA",
    savings: "$8,400",
    category: "Security Deposit",
    problem: "A landlord managing 3 rental units in San Francisco was charging 2x monthly rent as security deposits — standard practice for years. When California's AB 12 took effect, the limit dropped to 1x rent. The landlord was unaware of the change.",
    solution: "After uploading their lease to LeaseLenses, the AI immediately flagged the security deposit clause as a violation of current California law. The compliance report cited the specific statute (Civil Code §1950.5 as amended by AB 12) and recommended reducing deposits.",
    outcome: "The landlord adjusted all three leases before any tenant filed a complaint. Under California law, overcharging security deposits can result in up to 2x the deposit amount in damages per tenant. With deposits of $4,200 each, potential liability was $25,200 across three units.",
    risk_found: "Security deposit exceeds state maximum",
  },
  {
    title: "Property Manager Catches Missing Lead Paint Disclosure",
    location: "Chicago, IL",
    savings: "$19,507",
    category: "Federal Compliance",
    problem: "A property management company managing 12 pre-1978 buildings had been using a standardized lease template that didn't include the federally required lead-based paint disclosure. None of the 47 active leases had the required EPA pamphlet.",
    solution: "During a batch analysis of all leases, LeaseLenses flagged every single one as missing the lead paint disclosure. The AI identified this as a high-severity risk with potential penalties up to $19,507 per violation under federal law (42 U.S.C. §4852d).",
    outcome: "The company immediately began distributing the required disclosures and amendment addenda to all tenants. They also updated their template lease to include the disclosure by default. A single complaint to HUD could have triggered investigation of all 47 units.",
    risk_found: "Missing lead-based paint disclosure (pre-1978 building)",
  },
  {
    title: "Tenant Identifies Unfair Early Termination Clause",
    location: "Austin, TX",
    savings: "$3,600",
    category: "Contract Terms",
    problem: "A tenant was about to sign a lease that included a 3-month rent penalty for early termination, with no exceptions for military deployment, domestic violence, or other legally protected circumstances.",
    solution: "The tenant used LeaseLenses to review the lease before signing. The AI flagged the early termination clause as unusually harsh and noted that Texas law provides certain protections for military personnel (SCRA) that this clause didn't acknowledge.",
    outcome: "Armed with the Amendment Memo generated by LeaseLenses, the tenant negotiated the penalty down to 1 month's rent with exceptions for legally protected circumstances. The landlord agreed, preferring to modify the clause rather than lose a qualified tenant.",
    risk_found: "Excessive early termination penalty, missing legal exemptions",
  },
];

export default function CaseStudiesPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b bg-white">
        <div className="container mx-auto px-4 py-4 flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
            <ArrowLeft className="h-4 w-4 mr-2" />Back
          </Button>
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate("/")}>
            <FileText className="h-8 w-8 text-blue-600" />
            <span className="text-xl font-bold text-slate-800">LeaseLenses</span>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="text-center mb-12">
          <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
            Real Results from Real Users
          </h1>
          <p className="text-lg text-slate-600">
            See how landlords and tenants use LeaseLenses to protect themselves and save money.
          </p>
          <p className="text-sm text-slate-400 mt-2">Names and addresses anonymized for privacy.</p>
        </div>

        <div className="space-y-8">
          {CASE_STUDIES.map((study, idx) => (
            <Card key={idx} className="overflow-hidden">
              <div className="h-2 bg-gradient-to-r from-blue-500 to-green-500" />
              <CardContent className="py-8">
                {/* Header */}
                <div className="flex flex-wrap items-center gap-3 mb-4">
                  <Badge className="bg-blue-100 text-blue-700">{study.category}</Badge>
                  <Badge variant="secondary">{study.location}</Badge>
                  <Badge className="bg-green-100 text-green-700">
                    <DollarSign className="h-3 w-3 mr-1" />
                    {study.savings} saved
                  </Badge>
                </div>

                <h2 className="text-xl font-bold text-slate-800 mb-6">{study.title}</h2>

                <div className="grid md:grid-cols-3 gap-6">
                  {/* Problem */}
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <AlertTriangle className="h-4 w-4 text-red-500" />
                      <h3 className="font-semibold text-red-700">The Problem</h3>
                    </div>
                    <p className="text-sm text-slate-600">{study.problem}</p>
                  </div>

                  {/* Solution */}
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <Shield className="h-4 w-4 text-blue-500" />
                      <h3 className="font-semibold text-blue-700">What LeaseLenses Found</h3>
                    </div>
                    <p className="text-sm text-slate-600">{study.solution}</p>
                    <div className="mt-3 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
                      <p className="text-xs font-medium text-red-700">
                        Risk Flagged: {study.risk_found}
                      </p>
                    </div>
                  </div>

                  {/* Outcome */}
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <h3 className="font-semibold text-green-700">The Outcome</h3>
                    </div>
                    <p className="text-sm text-slate-600">{study.outcome}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* CTA */}
        <Card className="mt-12 bg-slate-800 border-slate-700">
          <CardContent className="py-8 text-center">
            <h2 className="text-2xl font-bold text-white mb-2">Don't Wait for Problems</h2>
            <p className="text-slate-300 mb-6">
              Analyze your lease now and catch issues before they become expensive.
            </p>
            <Button variant="secondary" size="lg" onClick={() => navigate("/dashboard")} className="gap-2">
              Start Free Analysis <ArrowRight className="h-4 w-4" />
            </Button>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
