import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createClient } from "@metagptx/web-sdk";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  FileText, ArrowLeft, Download, Mail, CheckCircle, 
  FileCheck, BookOpen, ClipboardList, Loader2
} from "lucide-react";
import { toast } from "sonner";

const client = createClient();

const TEMPLATES = [
  {
    id: "checklist",
    title: "Landlord Lease Review Checklist",
    description: "15-point checklist covering every critical clause a lease should include. Print it out and use it every time you review or create a lease.",
    icon: ClipboardList,
    badge: "Most Popular",
    badgeColor: "bg-blue-100 text-blue-700",
  },
  {
    id: "california",
    title: "California Lease Requirements Guide",
    description: "Complete guide to California-specific requirements including AB 1482, AB 12, security deposit rules, and required disclosures.",
    icon: BookOpen,
    badge: "State Guide",
    badgeColor: "bg-green-100 text-green-700",
  },
  {
    id: "general",
    title: "Standard Residential Lease Template Guide",
    description: "Section-by-section breakdown of what to include in a standard residential lease agreement, with sample language.",
    icon: FileCheck,
    badge: "Starter",
    badgeColor: "bg-slate-100 text-slate-700",
  },
];

export default function TemplatesPage() {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);

  const handleSubmit = async () => {
    if (!email || !selectedTemplate) return;
    if (!email.includes("@")) {
      toast.error("Please enter a valid email address");
      return;
    }

    setSubmitting(true);
    try {
      const response = await client.apiCall.invoke({
        url: "/api/v1/lease/lead/capture",
        method: "POST",
        data: { email, name, template_type: selectedTemplate },
      });

      if (response.data?.success) {
        setSubmitted(true);
        setDownloadUrl(response.data.download_url);
        toast.success("Template ready for download!");
      }
    } catch (err: any) {
      // Even if API fails, show success (lead capture is non-critical)
      setSubmitted(true);
      toast.success("Template ready!");
    } finally {
      setSubmitting(false);
    }
  };

  const handleDownload = async () => {
    if (!selectedTemplate) return;
    try {
      const response = await client.apiCall.invoke({
        url: `/api/v1/lease/template/${selectedTemplate}`,
        method: "GET",
      });

      const data = response.data;
      let content = `${data.title}\n${"=".repeat(50)}\n\n`;

      if (data.type === "checklist") {
        data.items?.forEach((item: string, idx: number) => {
          content += `☐ ${idx + 1}. ${item}\n\n`;
        });
      } else if (data.type === "guide") {
        data.sections?.forEach((section: any) => {
          content += `## ${section.title}\n${section.content}\n\n`;
        });
      }

      content += "\n---\nGenerated by LeaseLenses (leaselens.ai)\n";

      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `leaselens-${selectedTemplate}-template.txt`;
      document.body.appendChild(a);
      a.click();
      URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch {
      toast.error("Download failed. Please try again.");
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b bg-white">
        <div className="container mx-auto px-4 py-4 flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
            <ArrowLeft className="h-4 w-4 mr-2" />Back
          </Button>
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate("/")}>
            <FileText className="h-8 w-8 text-blue-600" />
            <span className="text-xl font-bold text-slate-800">LeaseLenses</span>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-3xl">
        <div className="text-center mb-12">
          <Badge className="bg-green-100 text-green-700 mb-4">Free Resources</Badge>
          <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
            Free Lease Templates & Guides
          </h1>
          <p className="text-lg text-slate-600">
            Download professional checklists, state guides, and template guides for free.
          </p>
        </div>

        {/* Template Selection */}
        <div className="space-y-4 mb-8">
          {TEMPLATES.map((template) => {
            const Icon = template.icon;
            const isSelected = selectedTemplate === template.id;
            return (
              <Card
                key={template.id}
                className={`cursor-pointer transition-all ${
                  isSelected ? "ring-2 ring-blue-500 border-blue-300" : "hover:shadow-md"
                }`}
                onClick={() => setSelectedTemplate(template.id)}
              >
                <CardContent className="py-5">
                  <div className="flex items-start gap-4">
                    <div className={`h-12 w-12 rounded-lg flex items-center justify-center flex-shrink-0 ${
                      isSelected ? "bg-blue-100" : "bg-slate-100"
                    }`}>
                      <Icon className={`h-6 w-6 ${isSelected ? "text-blue-600" : "text-slate-500"}`} />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-semibold text-slate-800">{template.title}</h3>
                        <Badge className={template.badgeColor}>{template.badge}</Badge>
                      </div>
                      <p className="text-sm text-slate-600">{template.description}</p>
                    </div>
                    <div className="flex-shrink-0">
                      <input
                        type="radio"
                        checked={isSelected}
                        onChange={() => setSelectedTemplate(template.id)}
                        className="h-5 w-5 text-blue-600"
                      />
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Email Capture Form */}
        {selectedTemplate && !submitted && (
          <Card className="border-blue-200">
            <CardHeader>
              <CardTitle className="text-lg">Get Your Free Template</CardTitle>
              <CardDescription>Enter your email to download instantly</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-sm font-medium text-slate-700 mb-1 block">Email *</label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-slate-700 mb-1 block">Name (optional)</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Your name"
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
              <Button
                className="w-full"
                size="lg"
                onClick={handleSubmit}
                disabled={!email || submitting}
              >
                {submitting ? (
                  <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Processing...</>
                ) : (
                  <><Download className="h-4 w-4 mr-2" />Download Free Template</>
                )}
              </Button>
              <p className="text-xs text-slate-400 text-center">
                We'll send you occasional tips. Unsubscribe anytime.
              </p>
            </CardContent>
          </Card>
        )}

        {/* Download Ready */}
        {submitted && (
          <Card className="border-green-200 bg-green-50">
            <CardContent className="py-8 text-center space-y-4">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto" />
              <h3 className="text-xl font-semibold text-green-800">Your Template is Ready!</h3>
              <Button size="lg" onClick={handleDownload} className="gap-2">
                <Download className="h-4 w-4" />
                Download Now
              </Button>
              <p className="text-sm text-green-700">
                Want AI-powered analysis?{" "}
                <button
                  onClick={() => navigate("/dashboard")}
                  className="underline font-medium"
                >
                  Sign up free
                </button>
              </p>
            </CardContent>
          </Card>
        )}
      </main>
    </div>
  );
}
